name: Build Zebra

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    -
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v2
        with:
            # Must be used to trigger workflow after push
            token: ${{ secrets.ACCESS_TOKEN }}

             # in forks, the token is not available - so we cannot us eit
    -
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/checkout@v2

    - name: Install Theos Dependencies
      run: brew install ldid fakeroot make

    - name: Install Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: gmake package
